CREATE TABLE feeds
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    feed_url   VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_feeds PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(255)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

CREATE TABLE subscriptions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid            UUID                                    NOT NULL,
    user_id         BIGINT,
    feed_id         BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    unsubscribed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_subscriptions PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id    BIGINT NOT NULL,
    user_roles VARCHAR(255)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE feeds
    ADD CONSTRAINT uc_feeds_uuid UNIQUE (uuid);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_tokenhash UNIQUE (token_hash);

ALTER TABLE subscriptions
    ADD CONSTRAINT uc_subscriptions_uuid UNIQUE (uuid);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_uuid UNIQUE (uuid);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_FEED FOREIGN KEY (feed_id) REFERENCES feeds (id);

ALTER TABLE subscriptions
    ADD CONSTRAINT FK_SUBSCRIPTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user_entity FOREIGN KEY (user_id) REFERENCES users (id);